### ISSUE TITLE
Cannot refresh access tokens

### ISSUE THREAD

**Issue by piotrpog** [venveo/craft-oauthclient#31]
I use plugin with google oauth. Not sure if it is problem with plugin, or I do something wrong on google end, but i cannot refresh access token, for example using CLI or by calling `refreshToken()` function directly.

I also noticed that each token has `refreshToken` property set to `null`.

**Comment by Mosnar** [comment]
@piotrpog This is actually more of a weird quirk with Google OAuth than a bug. If you don't request the token with "offline" permissions the very first time you authenticate, you will never receive a refresh token. The only way to get a refresh token after that is for the user to de-authorize the app in their Google settings.

You may be able to accomplish it by also forcing a re-prompt.

Take a look at this example:
https://github.com/venveo/craft-oauthclient#example-1-modifying-the-oauth-provider-settings

**Comment by piotrpog** [comment]
thanks for fast reply. i will test it tomorrow. btw, i think this info should be in readme :)
